version: "3.5"
services:
  calendar_db:
    container_name: calendar_db_prod
  calendar_api:
    container_name: calendar_api_prod
    image: calendar_api_prod:calendar
    build:
      target: production
  calendar_frontend:
    container_name: calendar_frontend_prod
    image: calendar_frontend_prod:calendar
    build:
      target: production
